### ISSUE TITLE
Cooldown for saving ship states

### ISSUE THREAD

**Issue by TomLewis** [APDevTeam/Movecraft-Repair#22]
Could we please get a cooldown so players cant spam create schematics of their ships.
Set in the config so we can set the time between how often they can be saving states of ships.

**Comment by TylerS1066** [comment]
What is the purpose of having a cooldown?

**Comment by TomLewis** [comment]
Players exploiting that they can to make hundreds of schematics just to be a pain, I've not tried it with large ships but I assume if players all spam created schematics of giant ships on repeat it would affect performance of the server.

They shouldn't be given the opportunity to do either as there is no limits for how many ship schematics they can create.

So the other option is to give them a limit.

You could save the same ship 10000 times if you wanted with a client to edit a sign an interact!

Always gotta think of the bad actors and never assume everyone is good and there to play fair!

**Comment by TylerS1066** [comment]
> Players exploiting that they can to make hundreds of schematics just to be a pain

I don't think that's a huge issue, if they use the same sign it'll just overwrite the same file again and again, barely causing any lag (Movecraft-Repair was heavily rewritten to be as fast as possible).

> I've not tried it with large ships but I assume if players all spam created schematics of giant ships on repeat it would affect performance of the server

My largest repair state (>50,000 blocks) is only 27KB, barely a blip on the storage needs of any server.  In fact, when you add up all 417 of my repair states on Airship Pirates, it's only 1.86MB.  Our server total repair states (including over 2000 player's states) is only 139MB.

> You could save the same ship 10000 times if you wanted with a client to edit a sign an interact!

That's a good point that I had not previously considered since AP is already running a few plugins that prevent sign editing.  I think a good solution to this that would be simple and 1.20 proof would be to disable editing of repair signs once placed.

**Comment by TylerS1066** [comment]
https://github.com/APDevTeam/Movecraft-Repair/commit/879554d0b007cbb7f6c535322b226bd7f8f67ca5 prevents repair signs from being edited, which resolves this issue.
